#!/bin/sh -l

#PBS -N comp_start
#PBS -q standby
#PBS -l nodes=1:ppn=1,naccesspolicy=singleuser
#PBS -l walltime=4:00:00
#PBS -e ../camels/blast.sterror
#PBS -o ../camels/blast.stout

cd /scratch/snyder/j/jwillou/camels
module load blast/2.9.0+

#makeblastdb -in dromedary.pbjelly.pilon.abyss.pilon.chromosomes.fasta -dbtype nucl
blastn -query primers_mod.fasta -db dromedary.pbjelly.pilon.abyss.pilon.chromosomes.fasta -out outblast.txt -outfmt 6 -perc_identity 10 -qcov_hsp_perc 10 -max_target_seqs 5 -word_size 7 -evalue 1000 -soft_masking FALSE 
