#!/bin/sh -l

#PBS -N comp_start
#PBS -q standby
#PBS -l nodes=1:ppn=1,naccesspolicy=singleuser
#PBS -l walltime=4:00:00
#PBS -e blast.sterror
#PBS -o blast.stout

cd /scratch/snyder/j/jwillou/camels
module load blast/2.9.0+

makeblastdb -in dromedary.pbjelly.pilon.abyss.pilon.chromosomes.fasta -dbtype nucl
blastn -query primers.fa -db dromedary.pbjelly.pilon.abyss.pilon.chromosomes.fasta -out outblast.txt -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore nident mismatch gapopen gaps qseq sseq' -perc_identity 80 -qcov_hsp_perc 80 -culling_limit 1 -max_target_seqs 5 -evalue 10 -num_threads 20
