#!/bin/sh -l

#PBS -N primersearch
#PBS -q standby
#PBS -l nodes=1:ppn=1,naccesspolicy=singleuser
#PBS -l walltime=4:00:00
#PBS -e ../camels/blast.sterror
#PBS -o ../camels/blast.stout

cd /scratch/snyder/j/jwillou/camels
#module load blast/2.9.0+
#makeblastdb -in dromedary.pbjelly.pilon.abyss.pilon.chromosomes.fasta -dbtype nucl

module load  EMBOSS/6.6.0

primersearch -seqall dromedary.pbjelly.pilon.abyss.pilon.chromosomes.fasta -infile query.txt -mismatchpercent 20 -outfile output.primersearch